spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        clientId: dummyId
                        clientSecret: dummySecret
